### PR TITLE
Implement I18n for internationalization support

### PR DESCRIPTION
**Pull request by CristianOliveiraDaRosa**
Reference for #216 pull request.
Squashed commits.

### CODE REVIEW

**Comment by tute** [comment]
Thank you!

**Comment by tute** [comment]
Released 2.3.2 with your change. Thanks!

**Comment by tute** [comment]
Released merit 2.3.2 with your change. Thanks!

**Comment by CristianOliveiraDaRosa** [comment]
It is awesome!

**Pull request merged**
